# Generated by Django 5.1.3 on 2024-12-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_rename_communities_communitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitie',
            name='banner',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
